openapi: 3.0.0
info:
  version: 1.0.0
  title: Care for Me APIs
  description: Care for Me APIs spec
paths:
  /list:
    get:
      description: Returns a list of stuff
      responses:
        '200':
          description: Successful response